// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofmevrrqeawyrtrubkzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mbWV2cnJxZWF3eXJ0cnVia3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDcyNTgsImV4cCI6MjA1OTkyMzI1OH0.-bBMyF0tAhaAl0LkJr4D700ETT5o95-Caoa7JrRmMCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);